import type { ScriptApiObject } from "../scripting-manager";

export type VisualizationDocsControl = {
    name: string;
    supportedUiTypes: string[];
    default?: Record<string, any> | null;
    required?: Record<string, any> | null;
};

export type VisualizationDocsShaderSource = {
    index: number;
    description?: string;
    acceptedChannelCounts?: number[] | null;
};

export type VisualizationDocsShader = {
    type: string;
    name: string;
    description?: string;
    preview?: string | null;
    sources: VisualizationDocsShaderSource[];
    controls: VisualizationDocsControl[];
    customParams: Array<{ name: string; usage?: string }>;
};

export type VisualizationDocsModel = {
    version: number;
    generatedAt: string;
    shaders: VisualizationDocsShader[];
    controls: Record<string, Array<{
        name: string;
        glType: string;
        uiType?: string;
        supports?: Record<string, any>;
    }>>;
};

export type VisualizationStateSnapshot = {
    data: DataSpecification[];
    visualizations: VisualizationItem[];
    activeVisualizationIndex?: Array<number | undefined>;
};

export type VisualizationViewportRenderOptions = {
    width?: number;
    height?: number;
    x?: number;
    y?: number;
    regionWidth?: number;
    regionHeight?: number;
    maxPixels?: number;
};

export type VisualizationViewportPixelsResult = {
    width: number;
    height: number;
    data: number[];
};

export type VisualizationFirstPassExtractOptions = {
    kind?: "texture" | "stencil";
    layerIndex?: number;
    width?: number;
    height?: number;
};

export type VisualizationLayerSource =
    | VisualizationItem
    | Record<string, VisualizationShaderLayer>;

export interface VisualizationScriptApi extends ScriptApiObject {
    /**
     * Lists the shader types that can be used in visualization layers.
     */
    getAvailableShaderTypes(): string[];

    /**
     * Returns the machine-friendly shader documentation model generated by the FlexRenderer shader configurator.
     */
    getShaderDocsModel(): VisualizationDocsModel;

    /**
     * Returns the shader documentation serialized as JSON.
     */
    getShaderDocsJson(pretty?: boolean): string;

    /**
     * Returns the shader documentation serialized as plain text.
     */
    getShaderDocsText(): string;

    /**
     * Returns the persisted visualization list for the current viewer session.
     */
    getVisualizations(): VisualizationItem[];

    /**
     * Returns the current active visualization selection.
     */
    getActiveVisualizationIndex(): Array<number | undefined> | undefined;

    /**
     * Returns the first active visualization entry, when one is selected.
     */
    getActiveVisualization(): VisualizationItem | undefined;

    /**
     * Captures the current visualization-related session state so it can be restored later.
     */
    captureState(): VisualizationStateSnapshot;

    /**
     * Restores a previously captured visualization state.
     * The user is asked for confirmation unless the scripting context bypasses consent dialogs.
     */
    restoreState(snapshot: VisualizationStateSnapshot): Promise<boolean>;

    /**
     * Changes the active visualization selection for the current viewer session.
     * The user is asked for confirmation unless the scripting context bypasses consent dialogs.
     */
    setActiveVisualization(index: number | number[]): Promise<boolean>;

    /**
     * Replaces the full visualization list for the current session.
     * Optional newData entries are appended to the session data array before the viewer reloads.
     */
    replaceVisualizations(
        visualizations: VisualizationItem[],
        activeVizIndex?: number | number[],
        newData?: DataID[]
    ): Promise<boolean>;

    /**
     * Adds a visualization to the current session.
     */
    addVisualization(
        visualization: VisualizationItem,
        options?: {
            makeActive?: boolean;
            newData?: DataID[];
        }
    ): Promise<boolean>;

    /**
     * Applies a partial patch to a persisted visualization entry.
     */
    updateVisualizationAt(
        index: number,
        patch: Partial<VisualizationItem>,
        options?: {
            makeActive?: boolean;
            newData?: DataID[];
        }
    ): Promise<boolean>;

    /**
     * Removes a visualization from the current session.
     */
    removeVisualization(index: number, nextActiveIndex?: number | number[]): Promise<boolean>;

    /**
     * Renders the current viewport with a temporary standalone visualization configuration and returns a PNG data URL.
     * For transient rendering, tiledImages should already resolve against the active viewer, or dataReferences must map to
     * data already present in the current session.
     */
    renderCurrentViewportPng(
        visualization: VisualizationLayerSource,
        options?: VisualizationViewportRenderOptions
    ): Promise<string>;

    /**
     * Renders the current viewport with a temporary standalone visualization configuration and returns raw RGBA pixels.
     */
    renderCurrentViewportPixels(
        visualization: VisualizationLayerSource,
        options?: VisualizationViewportRenderOptions
    ): Promise<VisualizationViewportPixelsResult>;

    /**
     * Extracts a first-pass texture or stencil layer from the active viewer's standalone renderer state.
     */
    extractCurrentFirstPassLayer(
        options?: VisualizationFirstPassExtractOptions
    ): Promise<VisualizationViewportPixelsResult>;
}
